<?php
$json_to_send = Mage::helper('core')->jsonDecode($this->renderDataAsJsonObject());

$items    = Mage::helper('core')->jsonEncode($json_to_send['items']); 
$purchase = Mage::helper('core')->jsonEncode($json_to_send['purchase']);

?>
<script type="text/javascript">
    crowdstream.events.addItems(<?php echo $items; ?>);

    crowdstream.events.checkout(<?php echo $purchase; ?>);
</script>    
